name: Security Scan

on:
- push
- pull_request

jobs:
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          sparse-checkout: go/
      - name: run gosec
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out results.sarif -stdout ./...
      - name: upload results
        uses: github/codeql-action/upload-sarif@v2
        continue-on-error: true
        with:
          sarif_file: results.sarif
      - name: run govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.19.0
           go-package: ./...
      - name: run govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.19.0
           go-package: ./...
