name: Security Scan

on:
- push
- pull_request

defaults:
  # would be nice if we could set this here:
  #runs-on: ubuntu-latest
  run:
    shell: bash

# Restrict permissions to a conservative set
permissions:
  # Check out repos
  contents: read
  # Post SARIF reports
  security-events: write
  # Required for running codeql-action/upload-sarif on private repos
  actions: read

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          sparse-checkout: go/
      - name: run gosec
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out gosec.sarif -stdout -verbose=text ./...
      - name: upload results
        uses: github/codeql-action/upload-sarif@v2
        # run this even when the gosec task fails (otherwise we wouldn't get a result)
        if: success() || failure()
        # but ignore errors in case GH security upload isn't available
        continue-on-error: true
        with:
          sarif_file: gosec.sarif
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          sparse-checkout: go/
      - name: run govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.19.0
           go-package: ./...
      # this action doesn't produce a SARIF report yet, so there's nothing to upload.
      # See: https://github.com/golang/go/issues/61347
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          sparse-checkout: terraform/
      - name: run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          format: lovely,sarif
          additional_args: --out results
      - name: upload results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        continue-on-error: true
        with:
          sarif_file: results.sarif.json
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          sparse-checkout: python/
      # Bandit doesn't include the SARIF formatter by default.
      # Also, it's not possible to generate screen output and SARIF results at the same time.
#      - name: run bandit
#        uses: PyCQA/bandit-action@v1.0.0
#        with:
#          args: |
#            -r -f screen,xml,yaml,json,sarif
      - name: install bandit
        run: |
          pip install bandit bandit_sarif_formatter
      - name: generate sarif report
        # ignore errors here (--exit-zero) so we can keep going
        run: |
          bandit --recursive --format sarif --output results.sarif --exit-zero python/
      - name: run bandit
        run: |
          bandit --recursive --format screen python/
      - name: upload results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        continue-on-error: true
        with:
          sarif_file: results.sarif
