name: Security Scan

on:
- push
- pull_request

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.19.0
           go-package: ./go/...
      - name: gosec
        uses: securego/gosec@master
        with:
          args: -fmt sarif -out results.sarif ./go/...
      - name: upload SARIF
        uses: github/codeql-action/upload-sarif@v1
        # ignore errors if GH Advanced Security is not availble
        continue-on-error: true
        with:
          sarif_file: results.sarif
